package com.foodrescue.foodrescue_be.dto.response;

import com.foodrescue.foodrescue_be.model.Voucher;
import lombok.Builder;
import lombok.Getter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Getter
@Builder
public class VoucherResponse {
    private Long id;
    private String name;
    private String code;
    private String description;
    private String discountType;
    private BigDecimal discountValue;
    private BigDecimal maxDiscountAmount;
    private BigDecimal minOrderValue;
    private Integer maxUses;
    private Integer usedCount;
    private LocalDateTime activeFrom;
    private LocalDateTime activeUntil;
    private Integer expiryHoursThreshold;
    private String targetProvince;
    private Integer comboItemThreshold;
    private Boolean autoTriggerEnabled;
    private Boolean autoGenerated;
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static VoucherResponse fromEntity(Voucher voucher) {
        Voucher.Status effectiveStatus = voucher.getStatus();
        if (voucher.getActiveUntil() != null
                && voucher.getActiveUntil().isBefore(LocalDateTime.now())
                && effectiveStatus == Voucher.Status.active) {
            effectiveStatus = Voucher.Status.expired;
        }

        return VoucherResponse.builder()
                .id(voucher.getId())
                .name(voucher.getName())
                .code(voucher.getCode())
                .description(voucher.getDescription())
                .discountType(voucher.getDiscountType() != null ? voucher.getDiscountType().name() : null)
                .discountValue(voucher.getDiscountValue())
                .maxDiscountAmount(voucher.getMaxDiscountAmount())
                .minOrderValue(voucher.getMinOrderValue())
                .maxUses(voucher.getMaxUses())
                .usedCount(voucher.getUsedCount())
                .activeFrom(voucher.getActiveFrom())
                .activeUntil(voucher.getActiveUntil())
                .expiryHoursThreshold(voucher.getExpiryHoursThreshold())
                .targetProvince(voucher.getTargetProvince())
                .comboItemThreshold(voucher.getComboItemThreshold())
                .autoTriggerEnabled(voucher.getAutoTriggerEnabled())
                .autoGenerated(voucher.getAutoGenerated())
                .status(effectiveStatus != null ? effectiveStatus.name() : null)
                .createdAt(voucher.getCreatedAt())
                .updatedAt(voucher.getUpdatedAt())
                .build();
    }
}
