spring:
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
