CREATE TABLE seller_wallet_transactions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    seller_id BIGINT NOT NULL,
    order_id BIGINT NULL,
    seller_order_id BIGINT NULL,
    payment_id BIGINT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    gross_amount DECIMAL(12,2) NOT NULL,
    commission_amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    description VARCHAR(255) NULL,
    reference_code VARCHAR(100) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_seller_wallet_order_credit UNIQUE (seller_order_id, type),
    CONSTRAINT fk_seller_wallet_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT fk_seller_wallet_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_seller_wallet_seller_order FOREIGN KEY (seller_order_id) REFERENCES order_seller_orders(id),
    CONSTRAINT fk_seller_wallet_payment FOREIGN KEY (payment_id) REFERENCES order_payments(id),
    INDEX idx_seller_wallet_seller_created (seller_id, created_at),
    INDEX idx_seller_wallet_status (status)
);
