package com.foodrescue.foodrescue_be.controller;

import com.foodrescue.foodrescue_be.dto.request.AdminVoucherUpsertRequest;
import com.foodrescue.foodrescue_be.dto.response.ResponseData;
import com.foodrescue.foodrescue_be.dto.response.VoucherResponse;
import com.foodrescue.foodrescue_be.model.Voucher;
import com.foodrescue.foodrescue_be.repository.VoucherRepository;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@RestController
@RequestMapping("/api/admin/vouchers")
@RequiredArgsConstructor
public class AdminVoucherController {

    private final VoucherRepository voucherRepository;

    @GetMapping
    public ResponseData<Page<VoucherResponse>> list(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String search,
            @RequestParam(required = false) Voucher.Status status,
            @RequestParam(required = false) Voucher.DiscountType discountType
    ) {
        String searchTrimmed = (search != null && !search.isBlank()) ? search.trim() : null;
        Page<VoucherResponse> result = voucherRepository.findAllFiltered(
                        searchTrimmed,
                        status,
                        discountType,
                        PageRequest.of(page, size, Sort.by("createdAt").descending())
                )
                .map(VoucherResponse::fromEntity);

        return ResponseData.ok(result);
    }

    @PostMapping
    public ResponseData<VoucherResponse> create(@RequestBody @Valid AdminVoucherUpsertRequest req) {
        String code = req.getCode().trim().toUpperCase();
        if (voucherRepository.existsByCodeIgnoreCase(code)) {
            throw new IllegalArgumentException("Mã voucher đã tồn tại");
        }

        Voucher voucher = Voucher.builder().build();
        applyRequest(voucher, req);
        voucher.setCode(code);
        if (voucher.getUsedCount() == null) voucher.setUsedCount(0);
        if (voucher.getAutoGenerated() == null) voucher.setAutoGenerated(false);

        Voucher saved = voucherRepository.save(voucher);
        return ResponseData.ok("Tạo voucher thành công", VoucherResponse.fromEntity(saved));
    }

    @PutMapping("/{id}")
    public ResponseData<VoucherResponse> update(
            @PathVariable Long id,
            @RequestBody @Valid AdminVoucherUpsertRequest req
    ) {
        Voucher voucher = voucherRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Voucher không tồn tại"));

        String code = req.getCode().trim().toUpperCase();
        if (voucherRepository.existsByCodeIgnoreCaseAndIdNot(code, id)) {
            throw new IllegalArgumentException("Mã voucher đã được sử dụng bởi voucher khác");
        }

        applyRequest(voucher, req);
        voucher.setCode(code);

        Voucher saved = voucherRepository.save(voucher);
        return ResponseData.ok("Cập nhật voucher thành công", VoucherResponse.fromEntity(saved));
    }

    @PutMapping("/{id}/status")
    public ResponseData<VoucherResponse> updateStatus(
            @PathVariable Long id,
            @RequestParam Voucher.Status status
    ) {
        Voucher voucher = voucherRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Voucher không tồn tại"));
        voucher.setStatus(status);
        return ResponseData.ok("Cập nhật trạng thái voucher thành công", VoucherResponse.fromEntity(voucherRepository.save(voucher)));
    }

    private void applyRequest(Voucher voucher, AdminVoucherUpsertRequest req) {
        validateRequest(req);

        voucher.setName(req.getName().trim());
        voucher.setDescription(req.getDescription() != null ? req.getDescription().trim() : null);
        voucher.setDiscountType(req.getDiscountType());
        voucher.setDiscountValue(req.getDiscountType() == Voucher.DiscountType.freeship ? BigDecimal.ZERO : req.getDiscountValue());
        voucher.setMaxDiscountAmount(req.getMaxDiscountAmount());
        voucher.setMinOrderValue(req.getMinOrderValue() != null ? req.getMinOrderValue() : BigDecimal.ZERO);
        voucher.setMaxUses(req.getMaxUses());
        voucher.setActiveFrom(req.getActiveFrom());
        voucher.setActiveUntil(req.getActiveUntil());
        voucher.setExpiryHoursThreshold(req.getExpiryHoursThreshold());
        voucher.setTargetProvince(req.getTargetProvince() != null ? req.getTargetProvince().trim() : null);
        voucher.setComboItemThreshold(req.getComboItemThreshold());
        voucher.setAutoTriggerEnabled(req.getAutoTriggerEnabled() != null ? req.getAutoTriggerEnabled() : false);

        Voucher.Status status = req.getStatus() != null ? req.getStatus() : Voucher.Status.active;
        if (req.getActiveUntil() != null && req.getActiveUntil().isBefore(LocalDateTime.now())) {
            status = Voucher.Status.expired;
        }
        voucher.setStatus(status);
    }

    private void validateRequest(AdminVoucherUpsertRequest req) {
        if (req.getName() == null || req.getName().trim().isEmpty()) {
            throw new IllegalArgumentException("Tên voucher không được để trống");
        }
        if (req.getCode() == null || req.getCode().trim().isEmpty()) {
            throw new IllegalArgumentException("Mã voucher không được để trống");
        }
        if (req.getDiscountValue() == null || req.getDiscountValue().compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Giá trị giảm phải lớn hơn hoặc bằng 0");
        }
        if (req.getDiscountType() == Voucher.DiscountType.percentage
                && req.getDiscountValue().compareTo(BigDecimal.valueOf(100)) > 0) {
            throw new IllegalArgumentException("Voucher phần trăm không được vượt quá 100");
        }
        if (req.getDiscountType() != Voucher.DiscountType.freeship
                && req.getDiscountValue().compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Giá trị giảm phải lớn hơn 0");
        }
        if (req.getMaxUses() != null && req.getMaxUses() <= 0) {
            throw new IllegalArgumentException("Số lượt sử dụng tối đa phải lớn hơn 0");
        }
        if (req.getMinOrderValue() != null && req.getMinOrderValue().compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Giá trị đơn tối thiểu không được âm");
        }
        if (req.getMaxDiscountAmount() != null && req.getMaxDiscountAmount().compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Mức giảm tối đa phải lớn hơn 0");
        }
        if (req.getActiveFrom() != null && req.getActiveUntil() != null && req.getActiveUntil().isBefore(req.getActiveFrom())) {
            throw new IllegalArgumentException("Thời gian kết thúc phải sau thời gian bắt đầu");
        }
        if (req.getExpiryHoursThreshold() != null && req.getExpiryHoursThreshold() <= 0) {
            throw new IllegalArgumentException("Ngưỡng giờ cận hạn phải lớn hơn 0");
        }
        if (req.getComboItemThreshold() != null && req.getComboItemThreshold() < 2) {
            throw new IllegalArgumentException("Combo phải có ít nhất 2 sản phẩm");
        }
    }
}
